using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using DataModel;

namespace StockManagement
{
    public partial class ManageProductsForm : Form
    {
        comp1690Entities _context;

        public ManageProductsForm()
        {
            InitializeComponent();
        }

        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);
            _context = new comp1690Entities();

            // Call the Load method to get the data for the given DbSet
            // from the database.
            // The data is materialized as entities. The entities are managed by
            // the DbContext instance.
            _context.Products.Load();
            _context.Warehouses.Load();

           /* this.warehouseBindingSource.DataSource =
                _context.Warehouses.Local.ToBindingList();*/

            // Bind the categoryBindingSource.DataSource to
            // all the Unchanged, Modified and Added Category objects that
            // are currently tracked by the DbContext.
            // Note that we need to call ToBindingList() on the
            // ObservableCollection<TEntity> returned by
            // the DbSet.Local property to get the BindingList<T>
            // in order to facilitate two-way binding in WinForms.
            this.productBindingSource.DataSource =
                _context.Products.Local.ToBindingList();

            DataGridViewComboBoxColumn box = this.DataGridViewComboBoxColumn;
            box.DataPropertyName = "Warehouse_Id";
            box.DataSource = _context.Warehouses.Local.ToBindingList();
            box.DisplayMember = "Name";
            box.ValueMember = "Id";

            DataGridView grid = this.stocksDataGridView;
            DataGridView grid2 = grid;
        }

        private void productBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            this.Validate();

            // Currently, the Entity Framework doesn’t mark the entities
            // that are removed from a navigation property (in our example the Products)
            // as deleted in the context.
            // The following code uses LINQ to Objects against the Local collection
            // to find all products and marks any that do not have
            // a Category reference as deleted.
            // The ToList call is required because otherwise
            // the collection will be modified
            // by the Remove call while it is being enumerated.
            // In most other situations you can do LINQ to Objects directly
            // against the Local property without using ToList first.
            foreach (var stock in _context.Stocks.Local.ToList())
            {
                if (stock.Product == null)
                {
                    _context.Stocks.Remove(stock);
                }
            }

            // Save the changes to the database. 
            this._context.SaveChanges();

            // Refresh the controls to show the values          
            // that were generated by the database. 
            this.stocksDataGridView.Refresh();
            this.productDataGridView.Refresh();

            // Update status label
            UpdateLabel("Saved!", System.Drawing.Color.ForestGreen, true);
        }

        

        private void productDataGridView_CellValueChanged(object sender, DataGridViewCellEventArgs e)
        {
            // Change occured, show it in label
            // Update status label
            UpdateLabel("State updated, save your changes", System.Drawing.Color.DarkOrange);
        }

        private void ManageProductsForm_Shown(object sender, EventArgs e)
        {
            this.productDataGridView.CellValueChanged += 
                new DataGridViewCellEventHandler(productDataGridView_CellValueChanged);
        }

        protected override void OnClosing(CancelEventArgs e)
        {
            base.OnClosing(e);
            this._context.Dispose();
        }

        private void UpdateLabel(string text, Color color, bool flash = false)
        {
            this.Invoke((MethodInvoker)delegate
            {
                this.toolStripStatusLabel1.Text = text;
                this.toolStripStatusLabel1.ForeColor = color;
                this.statusStrip1.Refresh();

                if (flash)
                {
                    System.Threading.Thread.Sleep(1000);
                    this.toolStripStatusLabel1.Text = "";
                    this.statusStrip1.Refresh();
                }
            });
        }
    }
}
