//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransfer
    {
        public StockTransfer()
        {
            this.StockTransferItems = new HashSet<StockTransferItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double Distance { get; set; }
    
        public virtual ICollection<StockTransferItem> StockTransferItems { get; set; }
        public virtual Warehouse Departure { get; set; }
        public virtual Warehouse Destination { get; set; }
    }
}
