//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StocksTransferItem
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual StocksTransfer StockTransfer { get; set; }
    }
}
