//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StocksTransfer
    {
        public StocksTransfer()
        {
            this.StockTransferItems = new ObservableListSource<StocksTransferItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Distance { get; set; }
    
        public virtual ObservableListSource<StocksTransferItem> StockTransferItems { get; set; }
        public virtual Warehouse Departure { get; set; }
        public virtual Warehouse Destination { get; set; }
    }
}
