//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StocksTransfer
    {
        public StocksTransfer()
        {
            this.StocksTransferItems = new HashSet<StocksTransferItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Distance { get; set; }
        public int DepartureId { get; set; }
        public int DestinationId { get; set; }
    
        public virtual ICollection<StocksTransferItem> StocksTransferItems { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
